const KEY = 'ziptop_city';
const cities = ['Новосибирск', 'Омск', 'Москва', 'Санкт-Петербург', 'Екатеринбург', 'Казань', 'Красноярск', 'Томск', 'Барнаул', 'Кемерово', 'Новокузнецк', 'Тюмень', 'Челябинск', 'Пермь', 'Уфа', 'Самара', 'Нижний Новгород', 'Ростов-на-Дону', 'Краснодар'];
const css = `.lazy-popup{position:fixed;inset:0;z-index:10000;display:grid;place-items:center;padding:18px;background:#0f172a9e;backdrop-filter:blur(5px);opacity:0;transition:opacity .2s}.lazy-popup.open{opacity:1}.city-modal{position:relative;width:min(660px,100%);max-height:min(660px,calc(100vh - 36px));overflow:auto;border-radius:18px;background:#fff;box-shadow:0 26px 72px #0f172a59;transform:translateY(14px) scale(.985);transition:transform .24s cubic-bezier(.2,0,0,1)}.lazy-popup.open .city-modal{transform:none}.city-modal__inner{padding:34px 38px 30px}.city-modal h2{margin:0;color:#18181b;font-size:34px;letter-spacing:-.04em;line-height:1}.city-modal__lead{margin:26px 0 20px;color:#18181b;font-size:18px}.city-modal__note{margin:0 0 24px;color:#71717a;font-size:16px;line-height:1.4}.city-modal label{display:grid;gap:9px;color:#27272a;font-size:15px}.city-modal input{box-sizing:border-box;width:100%;height:52px;border:2px solid #e4e4e7;border-radius:15px;padding:0 15px;color:#18181b;font:inherit;font-size:17px;outline:0}.city-modal input:focus{border-color:#fb5b08;box-shadow:0 0 0 4px #ffedd5}.city-modal__apply{width:100%;min-height:54px;margin:20px 0 24px;border:0;border-radius:15px;background:#ff9a76;color:#fff;font-size:17px;font-weight:800;cursor:pointer}.city-modal__chips{display:flex;flex-wrap:wrap;gap:9px}.city-modal__chip{min-height:38px;border:1px solid #e4e4e7;border-radius:999px;padding:0 15px;background:#fafafa;color:#18181b;font-size:14px;font-weight:700;cursor:pointer}.city-modal__chip:hover{border-color:#fb5b08;background:#fff7ed;color:#c2410c}.city-modal__auto{margin-top:24px;min-height:44px;border:0;border-radius:12px;padding:0 17px;background:#f1f1f1;color:#27272a;font-size:14px;font-weight:700;cursor:pointer}.city-modal__status{min-height:1.4em;margin:18px 0 0;color:#52525b;font-size:14px}.city-modal__close{position:absolute;top:12px;right:12px;display:grid;width:44px;height:44px;place-items:center;border:2px solid #fb5b08;border-radius:14px;background:#f4f4f5;color:#27272a;font-size:28px;line-height:1;cursor:pointer}@media(max-width:620px){.lazy-popup{padding:10px}.city-modal__inner{padding:28px 20px 24px}.city-modal h2{font-size:30px}.city-modal__lead{margin:22px 0 16px}.city-modal__note{margin-bottom:20px;font-size:14px}.city-modal__chip{min-height:36px;padding:0 12px;font-size:13px}}`;
const close = (root: HTMLElement) => { root.classList.remove('open'); setTimeout(() => root.remove(), 210); document.body.style.overflow = ''; };
const save = (city: string, root: HTMLElement) => { const value = city.trim(); if (!value) return; try { localStorage.setItem(KEY, value); localStorage.setItem('ziptop_city_manual', '1'); } catch {} window.dispatchEvent(new CustomEvent('ziptop:city-changed', { detail: value })); close(root); };
export function openCityModal() {
  document.getElementById('city-modal-root')?.remove(); const root = document.createElement('div'); root.id = 'city-modal-root'; root.className = 'lazy-popup';
  root.innerHTML = `<style>${css}</style><section class="city-modal" role="dialog" aria-modal="true" aria-labelledby="city-modal-title"><button class="city-modal__close" type="button" aria-label="Закрыть">×</button><div class="city-modal__inner"><h2 id="city-modal-title">Ваш город</h2><p class="city-modal__lead">Выберите город для ЗИПТОП.</p><p class="city-modal__note">Определение по IP приблизительное и может ошибаться при использовании VPN. Ручной выбор имеет приоритет.</p><label>Найти или ввести город<input type="search" autocomplete="address-level2" placeholder="Название города" data-city-input></label><button class="city-modal__apply" type="button" data-city-apply>Выбрать</button><div class="city-modal__chips" data-city-chips>${cities.map((city) => `<button class="city-modal__chip" type="button" data-city="${city}">${city}</button>`).join('')}</div><button class="city-modal__auto" type="button" data-city-auto>Определить автоматически</button><p class="city-modal__status" data-city-status></p></div></section>`;
  document.body.append(root); document.body.style.overflow = 'hidden'; requestAnimationFrame(() => root.classList.add('open'));
  const input = root.querySelector<HTMLInputElement>('[data-city-input]')!; const status = root.querySelector<HTMLElement>('[data-city-status]')!;
  root.querySelector('[data-city-apply]')?.addEventListener('click', () => save(input.value, root));
  root.querySelector('[data-city-chips]')?.addEventListener('click', (event) => { const city = (event.target as HTMLElement).closest<HTMLElement>('[data-city]')?.dataset.city; if (city) save(city, root); });
  input.addEventListener('input', () => { const query = input.value.trim().toLocaleLowerCase('ru-RU'); root.querySelectorAll<HTMLElement>('[data-city]').forEach((chip) => chip.hidden = Boolean(query) && !chip.textContent!.toLocaleLowerCase('ru-RU').includes(query)); });
  input.addEventListener('keydown', (event) => { if (event.key === 'Enter') save(input.value, root); });
  root.addEventListener('click', (event) => { if (event.target === root || (event.target as HTMLElement).closest('.city-modal__close')) close(root); });
  root.querySelector('[data-city-auto]')?.addEventListener('click', async () => { status.textContent = 'Определяем город…'; try { const response = await fetch('https://ipwho.is/?lang=ru'); const data = await response.json(); if (!data?.city) throw new Error(); input.value = data.city; status.textContent = `Определён город: ${data.city}`; } catch { status.textContent = 'Не удалось определить город. Выберите его вручную.'; } });
  window.addEventListener('keydown', (event) => { if (event.key === 'Escape') close(root); }, { once: true }); setTimeout(() => input.focus(), 160);
}
