type Product = { sku: string; name: string; category: string; price?: number; image: string; url: string; models?: string[] };
const initializedInputs = new WeakSet<HTMLInputElement>(); let catalog: Product[] | undefined; let request: Promise<Product[]> | undefined;
const money = new Intl.NumberFormat('ru-RU');
const normalize = (path: string) => path.replace(/^\/market(?=\/|$)/, '/каталог');
const load = (): Promise<Product[]> => request ||= fetch('/каталог/catalog-search.json')
  .then((response) => response.ok ? response.json() : Promise.reject())
  .then((data: unknown): Product[] => {
    const products = typeof data === 'object' && data !== null && 'products' in data ? data.products : [];
    return catalog = Array.isArray(products) ? products as Product[] : [];
  })
  .catch(() => catalog = []);
const score = (value: string, query: string) => { const text = value.toLocaleLowerCase('ru-RU'); if (text === query) return 100; if (text.startsWith(query)) return 80; const position = text.indexOf(query); if (position >= 0) return 60 - Math.min(20, position / 2); let index = 0; for (const letter of text) if (letter === query[index]) index += 1; return index === query.length && query.length > 1 ? 5 : 0; };
const search = async (raw: string) => { const query = raw.trim().toLocaleLowerCase('ru-RU'); if (!query) return []; const terms = query.split(/\s+/).filter(Boolean); return (await load()).map((product) => { const fields = [product.sku, product.name, product.category, ...(product.models || [])]; const value = Math.max(...fields.map((field) => score(field || '', query))); return { product, value: terms.every((term) => fields.some((field) => score(field || '', term) > 0)) ? value + 20 : value }; }).filter(({ value }) => value > 0).sort((a, b) => b.value - a.value).slice(0, 8).map(({ product }) => product); };
export function initLazyHeaderSearch() {
  const input = document.getElementById('header-search-input') as HTMLInputElement | null; const dropdown = document.getElementById('header-search-results') as HTMLDivElement | null; if (!input || !dropdown || initializedInputs.has(input)) return; initializedInputs.add(input);
  let selected = -1; let sequence = 0; const close = () => { sequence += 1; selected = -1; dropdown.hidden = true; input.setAttribute('aria-expanded', 'false'); };
  input.addEventListener('ziptop:search-close', close);
  const render = async () => { const query = input.value.trim(); if (!query) return close(); const current = ++sequence; if (!catalog) { dropdown.innerHTML = '<p class="search-loading">Загрузка каталога…</p>'; dropdown.hidden = false; } const results = await search(query); if (current !== sequence || query !== input.value.trim()) return; dropdown.replaceChildren(); selected = -1; if (!results.length) { const empty = document.createElement('p'); empty.className = 'search-empty'; empty.textContent = `Ничего не найдено по запросу «${query}».`; dropdown.append(empty); } for (const [index, product] of results.entries()) { const link = document.createElement('a'); link.className = 'search-result'; link.href = normalize(product.url); link.id = `search-item-${index}`; link.setAttribute('role', 'option'); const image = document.createElement('img'); image.className = 'search-result-img'; image.src = normalize(product.image); image.alt = ''; image.loading = 'lazy'; const info = document.createElement('span'); info.className = 'search-result-info'; const title = document.createElement('span'); title.className = 'search-result-title'; title.textContent = product.name; const meta = document.createElement('span'); meta.className = 'search-result-meta'; meta.textContent = `${product.category} · Арт. ${product.sku}`; info.append(title, meta); link.append(image, info); if (product.price) { const price = document.createElement('span'); price.className = 'search-result-price'; price.textContent = `${money.format(product.price)} ₽`; link.append(price); } dropdown.append(link); } dropdown.hidden = false; input.setAttribute('aria-expanded', 'true'); };
  input.addEventListener('input', () => void render()); input.addEventListener('keydown', (event) => { const items = Array.from(dropdown.querySelectorAll<HTMLAnchorElement>('.search-result')); if (event.key === 'Escape') return close(); if (event.key === 'ArrowDown' || event.key === 'ArrowUp') { event.preventDefault(); if (!items.length) return void render(); selected = (selected + (event.key === 'ArrowDown' ? 1 : -1) + items.length) % items.length; items.forEach((item, index) => item.classList.toggle('is-active', index === selected)); items[selected].scrollIntoView({ block: 'nearest' }); } if (event.key === 'Enter') { const target = items[selected >= 0 ? selected : 0]; if (target) { event.preventDefault(); target.click(); } } });
  document.addEventListener('pointerdown', (event) => { if (!(event.target as HTMLElement).closest('[data-search-island]')) close(); }); if (document.activeElement === input && input.value.trim()) void render();
}
